src/binder/create.rs
src/binder/mod.rs
src/binder/select.rs
src/catalog/column.rs
src/catalog/root.rs
src/catalog/table.rs
src/planner/logical_create_table_plan.rs
src/planner/operator/join.rs
src/planner/operator/scan.rs
src/types/mod.rs

add create table binding
Issue link: #8 
Tests 
- check the bind context should be used
- check  if `LogicalCreateTablePlan` struct define  is reasonable?
-  i had make some code format

feat(binder): add create table binding

---

src/binder/create.rs
src/binder/mod.rs
src/binder/select.rs
src/catalog/root.rs
src/main.rs
src/planner/logical_create_table_plan.rs
src/planner/logical_plan_builder.rs
src/planner/logical_select_plan.rs
src/planner/mod.rs
src/planner/operator/aggregate.rs
src/planner/operator/filter.rs
src/planner/operator/join.rs
src/planner/operator/limit.rs
src/planner/operator/mod.rs
src/planner/operator/project.rs
src/planner/operator/scan.rs
src/planner/operator/sort.rs

- add create table bind test
- change logic of main function
- bind context passing to planner
Tests 
Side effects
check context logic of passing

feat(flow): execute the sql process to arrive at the logic plan 

---

rust-toolchain
src/binder/create.rs
src/binder/expr.rs
src/binder/mod.rs
src/catalog/column.rs
src/catalog/mod.rs
src/catalog/root.rs
src/catalog/table.rs
src/db.rs
src/execution_v1/physical_plan/mod.rs
src/execution_v1/physical_plan/physical_create_table.rs
src/execution_v1/physical_plan/physical_plan_builder.rs
src/execution_v1/physical_plan/physical_projection.rs
src/execution_v1/physical_plan/physical_table_scan.rs
src/execution_v1/volcano_executor/create_table.rs
src/execution_v1/volcano_executor/mod.rs
src/expression/evaluator.rs
src/main.rs
src/planner/logical_create_table_plan.rs
src/planner/operator/create_table.rs
src/planner/operator/mod.rs
src/planner/operator/scan.rs
src/storage/memory.rs
src/storage/mod.rs
src/types/mod.rs

create table execute
Issue link: #5 
Tests 
Side effects
cargo fmt code
add rust-toolchain to enable ci

feat(execute): add create table PhysicalOperator

---

src/optimizer/heuristic/graph.rs

Issue link:
Tests 
Side effects

style(graph): split test

---

src/binder/create_table.rs
src/binder/insert.rs
src/binder/update.rs
src/expression/value_compute.rs
src/types/errors.rs
src/types/mod.rs
src/types/tuple.rs
src/types/value.rs

This commit revises the mechanism for checking limit conditions on variable length types such as varchar, moving the check from 'src/binder/insert.rs' to 'src/types/value.rs' to centralize the control. It also implements expression computation for the Udf8 data type. Furthermore, the now-unnecessary `Nvarchar` type has been removed. This overhaul enhances robustness against incorrect inputs in variable length fields and improves the computational abilities for the Utf8 data type.
Issue link:
Tests 
Side effects

feat: Refactor 'DataValue' length check logic; add support for varchar computations

---

src/binder/mod.rs
src/binder/show.rs
src/catalog/column.rs
src/db.rs
src/execution/executor/mod.rs
src/execution/executor/show/mod.rs
src/execution/executor/show/show_table.rs
src/planner/operator/mod.rs
src/planner/operator/show.rs
src/storage/kip.rs
src/storage/memory.rs
src/storage/mod.rs
src/storage/table_codec.rs

This commit introduces 'show tables' feature, allowing users to display table names in the database. Necessary changes were made in the execution module, database, binder, and storage to facilitate this feature. This includes addition of `ShowTables` struct and implementing the `Executor` trait for it, modifications in `Binder` to create a logical plan for 'show tables' commands, and adding `show_tables` function in storage to return a list of existing table names. Additionally, a 'ShowTablesOperator' was added in operator module to support operation, and new test cases were added to validate the modifications.
Tests 
Side effects

feat: Add 'show tables' functionality in SQL executor

---

Cargo.toml
src/binder/insert.rs
src/binder/update.rs
src/db.rs
src/expression/mod.rs
src/storage/table_codec.rs
src/types/errors.rs
src/types/mod.rs
src/types/value.rs
tests/slt/decimal

The database schema has been updated to support the Decimal data type. This includes casting from and to Decimal type in the DataValue structure, creating a new Decimal field in both LogicalType and DataValue structures, and adding appropriate match arms in the from_sqlparser_data_type and can_implicit_cast functions. A new error type for when an attempted conversion from Decimal fails have also been implemented. The round_dp_with_strategy method is used to provide flexibility with scale modification and rounding strategy when casting to Decimal type. Tests for the new functionality have been added as well.
Issue link:
Tests 
Side effects

feat(type): add support for Decimal type in database

---

README.md
src/binder/insert.rs
src/execution/executor/dml/insert.rs

Fix duplicate cast in insert
Tests 
Side effects

Fix duplicate cast in insert

---

README.md
src/binder/create_table.rs
src/catalog/column.rs
src/expression/evaluator.rs
src/expression/simplify.rs
src/optimizer/rule/simplification.rs
src/storage/table_codec.rs
src/types/mod.rs
src/types/value.rs
tests/slt/create.slt

Support text column in create table sql.
Part fixes https://github.com/KipData/KipSQL/issues/72
Tests 
Side effects

Support text column creation

---

src/execution/executor/dml/copy_from_file.rs

Several fields, 'text_files' and 'deleted_text_files', were added to the ColumnCatalog structure in the 'copy_from_file' module. The addition of these fields will allow the tracking of text files and deleted text files, enhancing error handling and data management.
Issue link:
Tests 
Side effects

fix: add text_files and deleted_text_files to ColumnCatalog

---

src/binder/expr.rs

feat: add bind_is_null
Issue link: https://github.com/KipData/KipSQL/issues/90
Tests 
Side effects

Feat: add bind_is_null

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/binder/aggregate.rs
src/binder/expr.rs
src/db.rs
src/execution/executor/dql/aggregate/hash_agg.rs
src/execution/executor/dql/aggregate/simple_agg.rs
src/execution/executor/dql/filter.rs
src/execution/executor/dql/join/hash_join.rs
src/execution/executor/dql/projection.rs
src/execution/executor/dql/sort.rs
src/expression/evaluator.rs
src/expression/mod.rs
src/optimizer/rule/column_pruning.rs
src/optimizer/rule/pushdown_predicates.rs
src/planner/operator/mod.rs
src/storage/kip.rs
src/storage/mod.rs
tests/slt/filter.slt

support `In` expression
- e.g. `select * from t1 where id in (1, 2)`
README beautification
Tests 
Side effects

Support `In` expression

---

.github/workflows/ci.yml
src/storage/mod.rs

Issue link: #98 
Tests 
Side effects

fix CacheError

---

src/binder/drop_table.rs
src/binder/mod.rs
src/execution/executor/ddl/drop_table.rs
src/planner/operator/drop_table.rs
src/storage/kip.rs
src/storage/mod.rs

Issue link: #105 
Tests 
Side effects

feat: support drop table if exists

---

Cargo.toml
examples/transaction.rs
src/binder/alter_table.rs
src/catalog/table.rs
src/execution/executor/ddl/alter_table/add_column.rs
src/execution/executor/ddl/alter_table/drop_column.rs
src/execution/executor/ddl/alter_table/mod.rs
src/execution/executor/mod.rs
src/optimizer/rule/column_pruning.rs
src/planner/operator/alter_table/drop_column.rs
src/planner/operator/alter_table/mod.rs
src/planner/operator/mod.rs
src/storage/kip.rs
src/storage/mod.rs
tests/slt/alter_table.slt
tests/slt/basic_test.slt

features:
- support drop column for alert table
- `alter table t1 drop column if exists v1`
- support `unique_index ` for add column
fmt
- `ColumnCatalog::add_index_meta`
Tests 
Side effects

feat: support drop column

---

src/binder/insert.rs
src/binder/mod.rs

Issue link:
#110 
Tests 
Side effects

fix(binder): insert column count validation

---

src/storage/table_codec.rs

Updating the outdated comments about `encode xx key` in TableCodec.
If there is a better way to describe the format of the key, please let me know.
Tests 
Side effects

docs: update TableCode comments

---

Cargo.toml
src/main.rs

❯ cargo run -- --path '/Users/xwg/dev/rust/KipSQL/data'
build the SQL layer of KipDB database
Usage: kip-sql [OPTIONS]
Options:
-p, --path <PATH>  Path to db file [default: ./data]
-h, --help         Print help
-V, --version      Print version
Tests 
Side effects

Feat: Add args path for main

---

Cargo.toml
src/binder/copy.rs
src/execution/executor/ddl/alter_table/add_column.rs
src/execution/executor/ddl/alter_table/drop_column.rs
src/execution/executor/ddl/create_table.rs
src/execution/executor/dml/copy_from_file.rs
src/execution/mod.rs
src/expression/value_compute.rs
src/planner/operator/copy_from_file.rs
src/types/errors.rs
src/types/tuple_builder.rs

refactor: `TupleBuiler` & `value_compute`

---

src/binder/create_table.rs
src/binder/delete.rs
src/binder/select.rs
src/db.rs
src/optimizer/rule/normalization/combine_operators.rs
src/optimizer/rule/normalization/mod.rs
tests/slt/group_by.slt

When `Distinct` and `GroupBy` exist at the same time, and `groupby_exprs` are consistent, Distinct can be eliminated.
Add Rule
- NormalizationRuleImpl::CollapseGroupByAgg
``` shell
28156=> explain select distinct a, b from t1 group by a, b; 
PLAN                                                                                                                                                                                                        
---------------------------------------------------
Projection [a, b] [Project]                      +
Aggregate [] -> Group By [a, b] [HashAggregate]+
Scan t1 -> [a, b] [SeqScan]
(1 row)
28156=> explain select distinct a, b, sum(k) from t1 group by a, b; 
PLAN …
```

perf: Eliminate duplicate aggregations

---

README.md
src/binder/aggregate.rs
src/binder/expr.rs
src/expression/evaluator.rs
src/expression/mod.rs
src/expression/simplify.rs
tests/slt/basic_test.slt
tests/slt/sql_2016/E021_06.slt
tests/slt/substring

`SELECT SUBSTRING ( 'foo' FROM 1 FOR 2 )`
Tests 
Side effects

feat: support `SUBSTRING()`

---

src/binder/aggregate.rs
src/binder/distinct.rs
src/catalog/table.rs
src/db.rs
src/execution/volcano/dql/aggregate/hash_agg.rs
src/execution/volcano/dql/join/hash_join.rs
src/expression/evaluator.rs
src/expression/mod.rs
src/expression/simplify.rs
src/optimizer/heuristic/graph.rs
src/optimizer/rule/normalization/column_pruning.rs
src/optimizer/rule/normalization/expression_remapper.rs
src/optimizer/rule/normalization/mod.rs
src/optimizer/rule/normalization/pushdown_predicates.rs
src/optimizer/rule/normalization/simplification.rs
src/planner/operator/aggregate.rs
src/planner/operator/mod.rs
src/storage/kip.rs
src/storage/table_codec.rs
src/types/index.rs

- feat: added `NormalizationRuleImpl::ColumnRemapper` to optimize expression mapping and avoid polling search
- fix: duplicate ColumnIds between multiple tables may cause constant relationship extraction errors
Tests 
Side effects

Optimize expression mapping

---

README.md
benchmarks/query_benchmark.rs
examples/hello_world.rs
examples/transaction.rs
src/bin/server.rs
src/binder/aggregate.rs
src/binder/create_table.rs
src/binder/expr.rs
src/binder/insert.rs
src/binder/mod.rs
src/db.rs
src/execution/volcano/dml/copy_from_file.rs
src/execution/volcano/dql/aggregate/avg.rs
src/execution/volcano/dql/aggregate/min_max.rs
src/execution/volcano/dql/aggregate/mod.rs
src/execution/volcano/dql/aggregate/sum.rs
src/expression/evaluator.rs
src/expression/function.rs
src/expression/mod.rs
src/expression/simplify.rs
src/expression/value_compute.rs
src/marcos/mod.rs
src/optimizer/core/memo.rs
src/storage/kip.rs
tests/sqllogictest/src/main.rs

```rust
function!(TestFunction::test(LogicalType::Integer, LogicalType::Integer) -> LogicalType::Integer => |v1: ValueRef, v2: ValueRef| {
let value = DataValue::binary_op(&v1, &v2, &BinaryOperator::Plus)?;
DataValue::unary_op(&value, &UnaryOperator::Minus)
});
```
```
select test(c1, 1) from test
+------------------+
| test(test.c1, 1) |
+==================+
| -2               |
|------------------|
| -3               |
|------------------|
| -2               |
|------------------|
| -4               |
+------------------+
```
Tips: 
The reason for supporting UDF is because SQL 2016 needs to support a large number of methods, and I don’t want to cause `ScalarExpression` to bloat, so UDF is supported to implement some functions in SQL 2016.
Tests 
Side effects

feat: support `UDF`

---

src/binder/insert.rs
src/binder/select.rs
src/errors.rs
src/execution/volcano/dql/join/hash_join.rs
tests/slt/basic_test.slt
tests/slt/group_by.slt
tests/slt/having.slt
tests/slt/select_into.slt
tests/slt/where.slt

- optimize HashJoin implementation
- support `Select Into`
```
EXPLAIN SELECT A INTO TABLE_E111_01_013 FROM TABLE_E111_01_011
+--------------------------------------------------------+
| PLAN                                                   |
+========================================================+
| Insert table_e111_01_013, Is Overwrite: false [Insert] |
|   Projection [table_e111_01_011.a] [Project]           |
|     Scan table_e111_01_011 -> [id, a] [SeqScan]        |
+--------------------------------------------------------+
```
Tips: I tried to implement `Semi/Anti` Join, but I didn’t have any good ideas
Tests 
Side effects

feat: support `Select Into`

---

src/expression/value_compute.rs
src/types/value.rs
tests/slt/crdb/and_or.slt
tests/slt/dummy.slt
tests/slt/filter.slt

- cast numeric to boolean
- `SELECT NOT(1::boolean)`
- `and/or` only has Null on one side
- `SELECT NULL AND false` -> false
Tests 
Side effects

fix: cast numeric to boolean and `and/or` only has Null on one side

---

src/binder/aggregate.rs
src/binder/expr.rs
src/binder/select.rs
src/db.rs
src/execution/volcano/dql/filter.rs
src/execution/volcano/mod.rs
src/expression/evaluator.rs
src/expression/mod.rs
src/expression/simplify.rs
src/expression/value_compute.rs
src/marcos/mod.rs
src/types/value.rs
tests/slt/crdb/condition.slt
tests/slt/dummy.slt
tests/slt/filter_null.slt
tests/slt/having.slt
tests/slt/subquery.slt
tests/sqllogictest/src/lib.rs
tests/sqllogictest/src/main.rs

- support `if()`/`ifnull()`/`nullif()`/`coalesce()`/`case ... when ...`
- add e2e test: `crdb/condition.slt`
- fix when performing equivalent calculations between Null and Null, Null should be returned.
Tests 
Side effects

feat: support `if()`/`ifnull()`/`nullif()`/`coalesce()`/`case ... when ...`

---

Cargo.toml
src/expression/simplify.rs
src/optimizer/rule/normalization/simplification.rs
tests/slt/dummy.slt
tests/slt/where_by_index.slt

fix case: 
```
query IIT
select * from t1 where id = 5 or (id > 5 and (id > 6 or id < 8)  and id < 12);
----
6 7 8
9 10 11
```
Tests 
Side effects

fix: range detection error when nesting `and` & `or`

---

src/binder/aggregate.rs
src/binder/expr.rs
src/expression/evaluator.rs
src/expression/mod.rs
src/expression/range_detacher.rs
src/expression/simplify.rs
tests/slt/sql_2016/E021_11.slt

Support for `POSITION()`  Function. `POSITION(pattern in s USING CHARACTERS/OCTETS)` is not implemented since it's not supported by sqlparser
Issue link: #130 
```sql
=> SELECT POSITION('bc' in 'abcd');
position(bc in abcd)
----------------------
2
(1 row)
=> SELECT POSITION('de' in 'abcd');
position(de in abcd)
----------------------
0
(1 row)
```
Tests 
Side effects

feat: add support for `POSITION()`

---

src/binder/select.rs
src/expression/evaluator.rs
src/planner/mod.rs
src/planner/operator/mod.rs
src/planner/operator/union.rs
tests/slt/substring.slt
tests/slt/tuple.slt
tests/slt/union.slt
tests/slt/update.slt

- fix: `substring` for out of bounds error 
- https://github.com/KipData/FnckSQL/issues/160
- feat: `substring` supports `from` expr as a negative number
- invalid: some slt files have incorrect file suffixes and are not allowed
Tests 
Side effects

fix: fucntion `substring` for out of bounds error

---

Cargo.toml
benchmarks/query_benchmark.rs
src/expression/simplify.rs

- fix benchmark errors in ubuntu environment
- `ScalarExpression::constant_calculation` adds new expression
Tests 
Side effects

invalid: fix `cfg(linux)` -> `cfg(unix)` & `ScalarExpression::constant_calculation` adds new expression

---

src/catalog/table.rs
src/execution/volcano/dml/analyze.rs
src/execution/volcano/dql/show_table.rs
src/optimizer/core/statistics_meta.rs
src/optimizer/rule/implementation/dql/scan.rs
src/planner/mod.rs
src/storage/kip.rs
src/storage/mod.rs
src/storage/table_codec.rs

Issue link: https://github.com/KipData/FnckSQL/issues/166
Tests 
Side effects

perf: Optimize `StatisticsMetaLoader::load`

---

src/binder/create_table.rs
src/binder/expr.rs
src/binder/mod.rs
src/db.rs
src/errors.rs
src/optimizer/core/memo.rs
tests/slt/subquery.slt

ref:
- https://github.com/duckdb/duckdb/blob/main/src/planner/binder/tableref/bind_subqueryref.cpp#L7C1-L31C2
Issue link: https://github.com/KipData/FnckSQL/issues/169
```shell
explain SELECT b FROM t1 WHERE a in (SELECT a FROM t2 where a in (select a from t1));
+-------------------------------------------------------------------------+
| PLAN                                                                    |
+=========================================================================+
| Projection [t1.b] [Project]                                             |
|   LeftSemi Join On t1.a = (t2.a) as (_temp_table_1_.a) [HashJoin]       |
|     Scan t1 -> [a, b] [SeqScan]                                         |
|     Projection [(t2.a) as (_temp_table_1_.a)] [Project]                 |
| …
```

fix: In multi-level nested subquery, the field relationships of different tables are wrong

---

src/binder/expr.rs
src/binder/insert.rs
src/binder/mod.rs

Change `bind_column_ref_from_identifiers`. Find table from bindings but not storage.
Issue link: #175 
```sql
explain select t.a from t1;
ERROR:  invalid table: t
```
Tests 
Side effects

fix:bind column incorrectly

---

Cargo.toml
src/binder/create_table.rs
src/binder/insert.rs
src/binder/update.rs
src/catalog/column.rs
src/db.rs
src/errors.rs
src/execution/volcano/ddl/add_column.rs
src/execution/volcano/dml/insert.rs
src/execution/volcano/dql/describe.rs
src/expression/function.rs
src/expression/mod.rs
src/marcos/mod.rs
src/storage/kip.rs
src/types/tuple.rs
tests/slt/create.slt

prefix function of `CURRENT_DATE` on SQL 2016
e.g.
on udf test
function: test(arg1, arg2)
`CREATE TABLE test (id int primary key, c1 int, c2 int default test(1, 2));`
Issue link:
Tests 
Side effects

feat: support `Expression` on `Default`

---

src/storage/table_codec.rs
src/types/mod.rs
src/types/value.rs

Insert 0u8 as the delimiter when encoding values ​​to avoid confusion when it is null.
Refer to `TableCodec::encode_index`
```rust
/// NonUnique Index:
/// Key: {TableName}{INDEX_TAG}{BOUND_MIN_TAG}{IndexID}{BOUND_MIN_TAG}{DataValue1}{BOUND_MIN_TAG}{DataValue2} .. {TupleId}
/// Value: TupleID
```
Tests 
Side effects

fix: memcomparable for `DataValue::Tuple`

---

src/binder/expr.rs
src/binder/mod.rs

Issue link: #192 
there is something wrong when binding correlated subqueries because parent context is ignored.
```sql
explain select a,b from t where a in (select a from t1 where a > t.a);
ERROR:  invalid table: t
```
This PR is to resolve this problem
the main idea is to take parent binder into consideration, too. After changing, it looks like this:
```sql
PLAN
------------------------------------------------------------------
Projection [t.a, t.b] [Project]                                 +
LeftSemi Join On t.a = (t1.a) as (_temp_table_0_.a) [HashJoin]+
Scan t -> [a, b] [SeqScan]                                  +
Projection [(t1.a) as (_temp_table_0_.a)] [Project]         +
Projection [t1.a] [Project]                               +
Filter (t1.a > t.a), Is Having: false [Filter] …
```

fix: bind correlated subqueries

---

src/storage/kip.rs
src/storage/mod.rs

Abstract the corresponding logic into `IndexImpl` according to different Indexes
Issue link: https://github.com/KipData/FnckSQL/issues/190
Tests 
Side effects

refactor: optimize the implementation of `IndexIter`

---

src/types/value.rs

chrono has deprecated some methods of NaiveDataTime: https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDateTime.html#method.from_timestamp I apply `cargo clippy` to correct it, and all tests are passed locally.
There're some compiling warnings related to some deprecated methods in `chrono::NaiveDataTime`.
Use the recommanded equal methods to replace the old ones.
Tests 
I ran `cargo test` locally in my machine and all of the testcases passed:
```
test result: ok. 99 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.60s
```
Side effects
It's a tiny refactor that doesn't alter the behavior of other codes.

refactor: eliminate the deprecation warning

---

Cargo.toml

update kipdb version up
scan reduces consumption by **`15%`**
```
FnckSQL: Full  Read by 'select * from t1'
time:   [107.80 ms 108.63 ms 109.44 ms]
change: [-16.754% -15.851% -14.928%] (p = 0.00 < 0.05)
Performance has improved.
SQLite: Full  Read by 'select * from t1'
time:   [44.343 ms 44.778 ms 45.563 ms]
change: [-2.2707% -0.4358% +1.5275%] (p = 0.67 > 0.05)
No change in performance detected.
FnckSQL: Point Read by 'select * from t1 where c1 = 1000'
time:   [30.191 µs 30.483 µs 30.813 µs]
change: [-0.0098% +1.3200% +2.7170%] (p = 0.10 > 0.05)
No change in performance detected.
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high mild
SQLite: Point Read by 'select * from t1 where c1 = 1000'
time:   [22.477 µs 22.875 µs 23.218 µs]
change: [-2.3707% -0.3802% +1.5986%] (p = …
```

config: kipdb version up

---

src/binder/aggregate.rs
src/binder/expr.rs
src/expression/evaluator.rs
src/expression/mod.rs
src/expression/range_detacher.rs
src/expression/simplify.rs
tests/slt/sql_2016/E021_09.slt

Generally, according to [E21_09](https://modern-sql.com/caniuse/E021-09), adds support for the method `TRIM()`.
Issue link: #130
Expression matching a pattern below will work fine:
```
TRIM([LEADING | TRAILING | BOTH] [trim_what FROM] exp)
```
Tests
Side effects
None

feat: add support for `TRIM()`

---

.github/workflows/ci.yml
src/db.rs
src/execution/dql/limit.rs
src/optimizer/rule/normalization/mod.rs
src/optimizer/rule/normalization/pushdown_limit.rs
tests/slt/crdb/limit.slt

test: add `crdb/limit.slt`
Tests 
Side effects

test: add `crdb/limit.slt`

---

src/execution/dql/join/nested_loop_join.rs
tests/slt/crdb/join.slt

Issue link: #206 
Add support for nested loop join
Some results does not mathe sql statements(e.g. column numbers, results order) in join.slt, so I changed some results or sql. 
And some sql may have wrong syntax, so I remain them commented.
Tests 
Side effects

support full join for nested loop join

---

src/execution/ddl/drop_column.rs
src/execution/dml/analyze.rs
src/storage/mod.rs
src/storage/table_codec.rs

Issue link: https://github.com/KipData/FnckSQL/issues/223
Tests 
Side effects

fix: expired statistics meta file clean

---

src/execution/dml/analyze.rs

Changed path directory retrieval from `dirs::config_dir` to `dirs::home_dir` in `analyze.rs`. This ensures the application uses the user's home directory for storing and accessing necessary metadata paths.
Issue link:
Tests 
Side effects

fix: use home directory instead of config directory for index paths avoid permission denied

---

src/binder/create_table.rs
src/binder/mod.rs
src/catalog/table.rs
src/db.rs
src/execution/dml/copy_from_file.rs
src/execution/dql/aggregate/hash_agg.rs
src/execution/dql/join/hash_join.rs
src/execution/dql/join/nested_loop_join.rs
src/execution/dql/sort.rs
src/expression/range_detacher.rs
src/optimizer/core/cm_sketch.rs
src/optimizer/core/histogram.rs
src/optimizer/core/memo.rs
src/optimizer/core/statistics_meta.rs
src/optimizer/heuristic/graph.rs
src/optimizer/heuristic/matcher.rs
src/optimizer/rule/normalization/column_pruning.rs
src/optimizer/rule/normalization/combine_operators.rs
src/optimizer/rule/normalization/pushdown_limit.rs
src/optimizer/rule/normalization/pushdown_predicates.rs
src/optimizer/rule/normalization/simplification.rs
src/storage/rocksdb.rs
src/storage/table_codec.rs
src/types/evaluator/mod.rs
src/types/tuple.rs
src/types/value.rs
src/utils/bit_vector.rs
src/utils/lru.rs

chore: `debug_assert!` -> `assert!` on test

---

README.md
tpcc/src/main.rs
tpcc/src/utils.rs

fix: test proportion of each scenario of `TPCC` and add more indicators

---

README.md
src/binder/copy.rs
src/execution/dml/copy_to_file.rs
src/execution/mod.rs
src/planner/mod.rs
src/planner/operator/copy_to_file.rs
tests/slt/copy.slt

Extended the COPY TO command to support exporting table data to CSV files. Enhanced the planning, execution, and test modules to handle the file writing mechanics and schema handling. Updated README to mark VIEW support as implemented and added relevant tests.
Tests 
Side effects

feat: Implement COPY TO functionality for exporting data to CSV.

---

src/binder/expr.rs
src/binder/mod.rs

this feature is not fully supported for the time being, and will be rolled back to pr 191 to avoid affecting user use.
link: https://github.com/KipData/FnckSQL/issues/192
Tests 
Side effects

chore: rollback `https://github.com/KipData/FnckSQL/pull/191`

---

README.md
src/bin/server.rs
src/binder/alter_table.rs
src/binder/copy.rs
src/binder/create_table.rs
src/binder/expr.rs
src/binder/mod.rs
src/binder/select.rs
src/db.rs
src/errors.rs
src/planner/operator/mod.rs
src/storage/mod.rs
src/storage/rocksdb.rs
src/storage/table_codec.rs
src/types/value.rs
tests/slt/where_by_index.slt
tpcc/README.md

- supplement decimal’s `memcomparable` encode
- todo code returns error
Tests 
Side effects

chore: supplement decimal’s `memcomparable` encode

---

Cargo.toml
src/bin/server.rs

Replaces custom handler implementations with a streamlined `PgWireServerHandlers` factory. Updates `pgwire` to version 0.28.0. This improves modularity and compatibility, simplifying query processing and error handling.
Issue link:
Tests 
Side effects

chore: refactor backend handlers and update `pgwire` dependency.

---

src/binder/mod.rs
src/binder/show_table.rs
src/binder/show_view.rs
src/execution/dql/mod.rs
src/execution/dql/show_view.rs
src/execution/mod.rs
src/optimizer/rule/normalization/column_pruning.rs
src/optimizer/rule/normalization/compilation_in_advance.rs
src/planner/mod.rs
src/planner/operator/mod.rs
src/storage/mod.rs
tests/slt/show_view.slt

The show view function is supported.
Tests 
Side effects

feat: Show View

---

README.md
src/execution/dql/index_scan.rs
src/storage/mod.rs

fix: https://github.com/KipData/KiteSQL/pull/263
Tests 
Side effects

fix: incorrect remapped primary key indices
