.github/pull_request_template.md

*: add pr template

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md

as tittle, and test (pr template)
Issue link:
Tests 
Side effects

*: add issue template

---

src/parser/mod.rs

Issue link:
Tests 
Side effects

fix(parser): doc test.

---

src/binder/create.rs
src/binder/mod.rs
src/catalog/column.rs
src/catalog/mod.rs
src/catalog/root.rs
src/catalog/table.rs
src/db.rs
src/lib.rs
src/main.rs
src/planner/logical_plan_builder.rs
src/planner/mod.rs
src/storage/mod.rs

- support create and select display
- support debugging multiple statements
Issue link:
Tests 
Side effects
- Ignore the logic of the storage table first
- Think about where to store the catalog 
- id ?
- location db or storage?

feat(storge): support create and select display plan

---

src/binder/create_table.rs
src/binder/insert.rs
src/binder/mod.rs
src/binder/select.rs
src/catalog/column.rs
src/catalog/table.rs
src/db.rs
src/execution/physical/physical_plan_builder.rs
src/execution_v1/physical_plan/mod.rs
src/execution_v1/physical_plan/physical_create_table.rs
src/execution_v1/physical_plan/physical_insert.rs
src/execution_v1/physical_plan/physical_plan_builder.rs
src/execution_v1/physical_plan/physical_values.rs
src/execution_v1/volcano_executor/create_table.rs
src/execution_v1/volcano_executor/insert.rs
src/execution_v1/volcano_executor/mod.rs
src/execution_v1/volcano_executor/values.rs
src/expression/mod.rs
src/planner/logical_create_table_plan.rs
src/planner/logical_insert_plan.rs
src/planner/mod.rs
src/planner/operator/create_table.rs
src/planner/operator/insert.rs
src/planner/operator/mod.rs
src/planner/operator/project.rs
src/planner/operator/values.rs
src/storage/memory.rs
src/storage/mod.rs
src/types/mod.rs
src/types/value.rs

Issue link:
Tests 
Side effects
supplementary unit testing is required

feat(insert): support sql insert simple syntax

---

src/binder/expr.rs
src/binder/select.rs
src/db.rs
src/execution_v1/physical_plan/mod.rs
src/execution_v1/physical_plan/physical_filter.rs
src/execution_v1/physical_plan/physical_plan_builder.rs
src/execution_v1/volcano_executor/filter.rs
src/execution_v1/volcano_executor/mod.rs
src/execution_v1/volcano_executor/table_scan.rs
src/expression/cast.rs
src/expression/mod.rs

Issue link:
Tests 
Side effects

feat(filter): implement the Filter physical operator

---

src/binder/select.rs
src/db.rs
src/execution/physical/physical_plan_builder.rs
src/execution_v1/physical_plan/mod.rs
src/execution_v1/physical_plan/physical_limit.rs
src/execution_v1/physical_plan/physical_plan_builder.rs
src/execution_v1/volcano_executor/limit.rs
src/execution_v1/volcano_executor/mod.rs
src/planner/operator/limit.rs

limit
Issue link: 
Tests 
Side effects

feat(limit): support physical limit operator

---

src/main.rs

Issue link:
Tests 
Side effects

fix: error print

---

.github/workflows/ci.yml
Cargo.toml
rust-toolchain
src/db.rs
src/lib.rs
src/main.rs

Input 'Enter' caused crash
Tests 
Side effects

fix(main): Add condition to skip empty user input. import data before looping

---

Cargo.toml
README.md

Issue link:
Tests 
Side effects

config: `Cargo.toml` add message for `cargo publish `

---

Cargo.toml
README.md
benchmarks/query_benchmark.rs
examples/hello_world.rs
examples/transaction.rs
src/db.rs
src/execution/volcano/dml/analyze.rs
src/main.rs
src/storage/kip.rs
tests/sqllogictest/Cargo.toml
tests/sqllogictest/src/lib.rs
tests/sqllogictest/src/main.rs

KipSQL -> FnckSQL
Tests 
Side effects

Rename: KipSQL -> FnckSQL

---

README.md
src/bin/server.rs
src/binder/analyze.rs
src/binder/copy.rs
src/binder/delete.rs
src/binder/describe.rs
src/binder/insert.rs
src/binder/mod.rs
src/binder/select.rs
src/catalog/table.rs
src/errors.rs
src/execution/volcano/dml/delete.rs
src/execution/volcano/dml/insert.rs
src/execution/volcano/dql/describe.rs
src/execution/volcano/dql/mod.rs
src/execution/volcano/mod.rs
src/optimizer/rule/normalization/column_pruning.rs
src/planner/operator/describe.rs
src/planner/operator/mod.rs
src/planner/operator/scan.rs
src/storage/kip.rs
src/storage/table_codec.rs
tests/slt/bigint.slt
tests/slt/describe.slt

- Describe
```shell
28156=> describe t1;
FIELD |  TYPE   | NULL  |   Key   | DEFAULT
-------+---------+-------+---------+---------
a     | INTEGER | false | PRIMARY | 
b     | INTEGER | true  | UNIQUE  | 
k     | INTEGER | false | EMPTY   |
z     | VARCHAR | true  | UNIQUE  |
(4 rows)
```
- Begin\Commit\Rollback
``` shell
28156=> begin;
OK
28156=> select * from t1;
a  | b | k | z
-----+---+---+----
-99 | 1 | 1 | k
-1 | 2 | 2 | i
5 | 3 | 2 | p
29 | 4 | 2 | db
(4 rows)
28156=> insert into t1 values(9,5,2,'u'); 
--
(0 rows)
28156=> select * from t1;
a  | b | k | z
-----+---+---+----
-99 | 1 | 1 | k
-1 | 2 | 2 | i
5 | 3 | 2 | p
9 | 5 | 2 | u
29 | 4 | 2 | db
(5 rows)
28156=> rollback;
OK
28156=> select * from t1;
a  | b | k | z …
```

Support: `Describe` & `Begin\Commit\Rollback` on Server

---

src/expression/range_detacher.rs

fix: `RangeDetacher::check_or` incorrect handling of case: `c1 > 1 or c2 > 1`
Tests 
Side effects

fix: `RangeDetacher::check_or` incorrect handling of case: `c1 > 1 or c2 > 1`

---

Cargo.toml

Update FnckSQL keywords in crates.io
Tests 
Side effects

config: Cargo.toml

---

.github/workflows/ci.yml

Fix errors in pr: https://github.com/KipData/FnckSQL/pull/164
Tests 
Side effects

config: ci rust toolchain -> nightly-2024-01-17

---

Cargo.toml
README.md

add Cross Join for DQL and Contributors
Tests 
Side effects

doc: add Cross Join for DQL and Contributors

---

Dockerfile
README.md

Add docker support
- Dockerfile
- README.md

feat: Add docker support

---

Cargo.toml
README.md
benchmarks/query_benchmark.rs
src/bin/server.rs
src/lib.rs
src/main.rs
src/storage/rocksdb.rs
tests/slt/sql_2016/E021_04.slt

Migrated the PG Wire service back and updated the documentation of lib.rs
Tests 
Side effects

feat: support pgwire

---

src/binder/create_table.rs
src/binder/mod.rs
src/db.rs
src/execution/ddl/add_column.rs
src/execution/ddl/drop_column.rs
src/execution/dml/copy_from_file.rs
src/execution/dml/delete.rs
src/execution/dml/insert.rs
src/execution/dml/update.rs
src/execution/dql/aggregate/hash_agg.rs
src/execution/dql/join/hash_join.rs
src/execution/dql/join/nested_loop_join.rs
src/storage/mod.rs
src/storage/rocksdb.rs
src/types/index.rs
tests/slt/crdb/join.slt

test: add unit tests for `Transaction`

---

src/db.rs
src/function/lower.rs
src/function/mod.rs
src/function/upper.rs
tests/slt/sql_2016/E021_08.slt

Add functions Lower & Upper
Tests 
Side effects

feat: add function Lower & Upper

---

src/binder/create_table.rs
src/binder/mod.rs
src/db.rs
src/errors.rs
src/execution/dql/aggregate/hash_agg.rs
src/execution/dql/join/hash_join.rs
src/execution/dql/join/nested_loop_join.rs
src/expression/mod.rs
src/serdes/column.rs
src/storage/mod.rs
src/storage/rocksdb.rs
src/utils/lru.rs

chore: remove useless arc on lru

---

README.md
docs/features.md
tpcc/README.md

Rewrite `README.md`
Tests 
Side effects

docs: README

---

README.md

fixed a broken sentence in the documentation.
Issue link:
Tests 
Side effects

fixed the broken sentence in introduction.

---

Cargo.lock
Cargo.toml
src/planner/operator/table_scan.rs

chore: v0.1.2
